# Cloudflare Pages configuration
name = "insightlead"
compatibility_date = "2023-05-18"
pages_build_output_dir = "dist"

[build]
command = "bun install && bun run build:prod"
cwd = ""
watch_dir = "src"

[build.environment]
BUN_VERSION = "latest"

[[build.environment_variables]]
NODE_ENV = "production"
VITE_USE_MOCK_DATA = "false"
VITE_SEED_INDEXEDDB = "false"